[package]
name = "advent"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
itertools = "0.13.0"
num = "0.4.1"
once_cell = "1.18.0"
rayon = "1.8.0"
regex = "1.10.2"
